[package]
name = "zk-router"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wasmparser = { workspace = true }
wasmtime = { workspace = true }

[features]
default = []
